version: '3.8'
services:
  web:
    build: .
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://***:***@db:5432/***
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ***
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
